### ISSUE TITLE
Snap zoom in

### ISSUE THREAD

**Issue by nupoormonani** [Siqister/cartodb_test_app#24]
- [x] Set up viewports at three scales: statewide, city and district. (Double clicking on statewide map zooms in to the citywide scale)
- [x] Add zoom bar

**Comment by allthesignals** [comment]
@nupoormonani I could use a little more guidance on how this will work. This is a slippy map interface, so users are able to pan and zoom anywhere. I've added a zoom bar, but I'm not sure how the first bullet point will work. By default, double-click adjusts the zoom level by one. So, it sounds like we could override that default where double-clicking adjusts the zoom level by five, but it could put users in a random part of the map. 

I think having the cities on the left zoom to their respective district bounding boxes when clicking (instead of just centering) would accomplish what we need for this issue. Thoughts? Feel free to sketch some things out here if you need: https://wireframe.cc.

**Comment by nupoormonani** [comment]
@allthesignals I think icon clustering solves this issue - at the state-wide zoom, a user would intuitively click on the cluster marker, which snaps to the district-scale.
