### ISSUE TITLE
Basemap updates (Utile)

### ISSUE THREAD

**Issue by nupoormonani** [Siqister/cartodb_test_app#27]
Statewide scale:
- [x] Remove Malden, Everett
- [x] Open space
- [x] City limits
- [x] Highways and rail lines

City scale:
- [x] Open space
- [x] Public transit
- [x] Street widths, street names

**Comment by IanJakus** [comment]
Currently there are no parcels associated with Malden and Everett. 
At statewide scale only show Massachusetts State

City Scale:
Sidewalks table for future. 
Nupoor were you thinking citywide parcels rather than just district parcels?

District Scale:
historic district and property data we can easily add but this can wait until next scope.

**Comment by nupoormonani** [comment]
To review during July 05 meeting

**Comment by allthesignals** [comment]
Added

**Comment by IanJakus** [comment]
- [x] Still seeing non-MBTA transit stops as black dots. 
- [x] Transit stops are not aligning with rail lines

**Comment by nupoormonani** [comment]
@IanJakus Both above points resolved. I'm not able to check the box maybe @allthesignals can help?

**Comment by allthesignals** [comment]
Closing this, @IanJakus
