### ISSUE TITLE
Default to showing only "activating" type points

### ISSUE THREAD

**Issue by allthesignals** [Siqister/cartodb_test_app#35]

**Comment by allthesignals** [comment]
@IanJakus, @nupoormonani 

I just made this change, but very few markers show up by default. I'm going to push this and see what the team thinks.

**Comment by allthesignals** [comment]
Closing for now until further review. Please reopen issue if this is not going to work.

**Comment by IanJakus** [comment]
@allthesignals 

While we are going to do a full business inventory for each district, the point with the 'activating' filter is to demonstrate what we think the districts most important assets are. I like defaulting with the filter on, but would like the option to take it off in order to see the full inventory for data entry.

**Comment by allthesignals** [comment]
@IanJakus the toggle is still available when you click a specific city. I think that toggle could be better placed within the UI.
